// ReSharper disable InconsistentNaming
// ReSharper disable UnusedMember.Global

namespace DELTation.ToonShader.Custom
{
	public enum CustomToonShaderHookType
	{
		TOON_SHADER_HOOK_INPUT_BUFFER,
		TOON_SHADER_HOOK_INPUT_TEXTURES,
		TOON_SHADER_HOOK_FRAGMENT_ALBEDO,
		TOON_SHADER_HOOK_VERTEX_INPUT,
		TOON_SHADER_HOOK_APP_DATA,
		TOON_SHADER_CUSTOM_INSTANCING_BUFFER,
		TOON_SHADER_CUSTOM_CBUFFER,
		TOON_SHADER_HOOK_FORWARD_PASS_V2F,
		TOON_SHADER_HOOK_VERTEX_OUTPUT,
		TOON_SHADER_HOOK_RAMP_BRIGHTNESS,
	}
}